import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Objects;

public class CrearUsuario {
    private JTextField textField1;
    private JTextField textField2;
    private JTextField textField3;
    private JTextField textField4;
    private JPasswordField passwordField1;
    private JCheckBox mostrarContraseñaCheckBox;
    private JPasswordField passwordField2;
    private JPasswordField passwordField3;
    private JComboBox comboBox1;
    private JTextField textFieldnombremascota1;
    private JComboBox JComboBoxtipomascota1;
    private JComboBox JComboBoxsexomascota1;
    private JComboBox JComboBoxalimentomascota1;
    private JLabel nombremascota1;
    private JLabel nombremascota2;
    private JLabel nombremascota3;
    private JLabel nombremascota4;
    private JLabel nombremascota5;
    private JLabel nombremascota6;
    private JLabel nombremascota7;
    private JLabel nombremascota8;
    private JLabel nombremascota9;
    private JTextField textFieldnombremascota2;
    private JTextField textFieldnombremascota3;
    private JTextField textFieldnombremascota4;
    private JTextField textFieldnombremascota5;
    private JTextField textFieldnombremascota6;
    private JTextField textFieldnombremascota7;
    private JTextField textFieldnombremascota8;
    private JTextField textFieldnombremascota9;
    private JLabel tipomascota1;
    private JLabel tipomascota2;
    private JLabel tipomascota3;
    private JLabel tipomascota4;
    private JLabel tipomascota5;
    private JLabel tipomascota6;
    private JLabel tipomascota7;
    private JLabel tipomascota8;
    private JLabel tipomascota9;
    private JComboBox JComboBoxtipomascota9;
    private JComboBox JComboBoxtipomascota8;
    private JComboBox JComboBoxtipomascota7;
    private JComboBox JComboBoxtipomascota6;
    private JComboBox JComboBoxtipomascota5;
    private JComboBox JComboBoxtipomascota4;
    private JComboBox JComboBoxtipomascota3;
    private JComboBox JComboBoxtipomascota2;
    private JLabel razamascota1;
    private JLabel razamascota2;
    private JLabel razamascota3;
    private JLabel razamascota4;
    private JLabel razamascota5;
    private JLabel razamascota6;
    private JLabel razamascota7;
    private JLabel razamascota8;
    private JLabel razamascota9;
    private JTextField textFieldrazamascota9;
    private JTextField textFieldrazamascota8;
    private JTextField textFieldrazamascota7;
    private JTextField textFieldrazamascota6;
    private JTextField textFieldrazamascota5;
    private JTextField textFieldrazamascota4;
    private JTextField textFieldrazamascota3;
    private JTextField textFieldrazamascota2;
    private JTextField textFieldrazamascota1;
    private JLabel edadmascota1;
    private JLabel edadmascota2;
    private JLabel edadmascota3;
    private JLabel edadmascota4;
    private JLabel edadmascota5;
    private JLabel edadmascota6;
    private JLabel edadmascota7;
    private JLabel edadmascota8;
    private JLabel edadmascota9;
    private JTextField textFieldedadmascota9;
    private JTextField textFieldedadmascota8;
    private JTextField textFieldedadmascota7;
    private JTextField textFieldedadmascota6;
    private JTextField textFieldedadmascota5;
    private JTextField textFieldedadmascota4;
    private JTextField textFieldedadmascota3;
    private JTextField textFieldedadmascota2;
    private JTextField textFieldedadmascota1;
    private JLabel sexomascota1;
    private JLabel sexomascota2;
    private JLabel sexomascota3;
    private JLabel sexomascota4;
    private JLabel sexomascota5;
    private JLabel sexomascota6;
    private JLabel sexomascota7;
    private JLabel sexomascota8;
    private JLabel sexomascota9;
    private JComboBox JComboBoxsexomascota9;
    private JComboBox JComboBoxsexomascota8;
    private JComboBox JComboBoxsexomascota7;
    private JComboBox JComboBoxsexomascota6;
    private JComboBox JComboBoxsexomascota5;
    private JComboBox JComboBoxsexomascota4;
    private JComboBox JComboBoxsexomascota3;
    private JComboBox JComboBoxsexomascota2;
    private JLabel alimentomascota1;
    private JLabel alimentomascota2;
    private JLabel alimentomascota3;
    private JLabel alimentomascota4;
    private JLabel alimentomascota5;
    private JLabel alimentomascota6;
    private JLabel alimentomascota7;
    private JLabel alimentomascota8;
    private JLabel alimentomascota9;
    private JComboBox JComboBoxalimentomascota9;
    private JComboBox JComboBoxalimentomascota8;
    private JComboBox JComboBoxalimentomascota7;
    private JComboBox JComboBoxalimentomascota6;
    private JComboBox JComboBoxalimentomascota5;
    private JComboBox JComboBoxalimentomascota4;
    private JComboBox JComboBoxalimentomascota3;
    private JComboBox JComboBoxalimentomascota2;
    private JButton GUARDARButton;
    private JPanel crearusuario;
    private JLabel mascota1;
    private JLabel mascota2;
    private JLabel mascota3;
    private JLabel mascota4;
    private JLabel mascota5;
    private JLabel mascota6;
    private JLabel mascota7;
    private JLabel mascota8;
    private JLabel mascota9;
    private JScrollPane Scroll;

    public CrearUsuario(){

        comboBox1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int seleccion = Integer.parseInt((String) Objects.requireNonNull(comboBox1.getSelectedItem()));

                if (seleccion == 1){
                    mascota2.setVisible(false);
                    nombremascota2.setVisible(false);
                    textFieldnombremascota2.setVisible(false);
                    tipomascota2.setVisible(false);
                    JComboBoxtipomascota2.setVisible(false);
                    razamascota2.setVisible(false);
                    textFieldrazamascota2.setVisible(false);
                    edadmascota2.setVisible(false);
                    textFieldedadmascota2.setVisible(false);
                    sexomascota2.setVisible(false);
                    JComboBoxsexomascota2.setVisible(false);
                    alimentomascota2.setVisible(false);
                    JComboBoxalimentomascota2.setVisible(false);

                    mascota3.setVisible(false);
                    nombremascota3.setVisible(false);
                    textFieldnombremascota3.setVisible(false);
                    tipomascota3.setVisible(false);
                    JComboBoxtipomascota3.setVisible(false);
                    razamascota3.setVisible(false);
                    textFieldrazamascota3.setVisible(false);
                    edadmascota3.setVisible(false);
                    textFieldedadmascota3.setVisible(false);
                    sexomascota3.setVisible(false);
                    JComboBoxsexomascota3.setVisible(false);
                    alimentomascota3.setVisible(false);
                    JComboBoxalimentomascota3.setVisible(false);

                    mascota4.setVisible(false);
                    nombremascota4.setVisible(false);
                    textFieldnombremascota4.setVisible(false);
                    tipomascota4.setVisible(false);
                    JComboBoxtipomascota4.setVisible(false);
                    razamascota4.setVisible(false);
                    textFieldrazamascota4.setVisible(false);
                    edadmascota4.setVisible(false);
                    textFieldedadmascota4.setVisible(false);
                    sexomascota4.setVisible(false);
                    JComboBoxsexomascota4.setVisible(false);
                    alimentomascota4.setVisible(false);
                    JComboBoxalimentomascota4.setVisible(false);

                    mascota5.setVisible(false);
                    nombremascota5.setVisible(false);
                    textFieldnombremascota5.setVisible(false);
                    tipomascota5.setVisible(false);
                    JComboBoxtipomascota5.setVisible(false);
                    razamascota5.setVisible(false);
                    textFieldrazamascota5.setVisible(false);
                    edadmascota5.setVisible(false);
                    textFieldedadmascota5.setVisible(false);
                    sexomascota5.setVisible(false);
                    JComboBoxsexomascota5.setVisible(false);
                    alimentomascota5.setVisible(false);
                    JComboBoxalimentomascota5.setVisible(false);

                    mascota6.setVisible(false);
                    nombremascota6.setVisible(false);
                    textFieldnombremascota6.setVisible(false);
                    tipomascota6.setVisible(false);
                    JComboBoxtipomascota6.setVisible(false);
                    razamascota6.setVisible(false);
                    textFieldrazamascota6.setVisible(false);
                    edadmascota6.setVisible(false);
                    textFieldedadmascota6.setVisible(false);
                    sexomascota6.setVisible(false);
                    JComboBoxsexomascota6.setVisible(false);
                    alimentomascota6.setVisible(false);
                    JComboBoxalimentomascota6.setVisible(false);

                    mascota7.setVisible(false);
                    nombremascota7.setVisible(false);
                    textFieldnombremascota7.setVisible(false);
                    tipomascota7.setVisible(false);
                    JComboBoxtipomascota7.setVisible(false);
                    razamascota7.setVisible(false);
                    textFieldrazamascota7.setVisible(false);
                    edadmascota7.setVisible(false);
                    textFieldedadmascota7.setVisible(false);
                    sexomascota7.setVisible(false);
                    JComboBoxsexomascota7.setVisible(false);
                    alimentomascota7.setVisible(false);
                    JComboBoxalimentomascota7.setVisible(false);

                    mascota8.setVisible(false);
                    nombremascota8.setVisible(false);
                    textFieldnombremascota8.setVisible(false);
                    tipomascota8.setVisible(false);
                    JComboBoxtipomascota8.setVisible(false);
                    razamascota8.setVisible(false);
                    textFieldrazamascota8.setVisible(false);
                    edadmascota8.setVisible(false);
                    textFieldedadmascota8.setVisible(false);
                    sexomascota8.setVisible(false);
                    JComboBoxsexomascota8.setVisible(false);
                    alimentomascota8.setVisible(false);
                    JComboBoxalimentomascota8.setVisible(false);

                    mascota9.setVisible(false);
                    nombremascota9.setVisible(false);
                    textFieldnombremascota9.setVisible(false);
                    tipomascota9.setVisible(false);
                    JComboBoxtipomascota9.setVisible(false);
                    razamascota9.setVisible(false);
                    textFieldrazamascota9.setVisible(false);
                    edadmascota9.setVisible(false);
                    textFieldedadmascota9.setVisible(false);
                    sexomascota9.setVisible(false);
                    JComboBoxsexomascota9.setVisible(false);
                    alimentomascota9.setVisible(false);
                    JComboBoxalimentomascota9.setVisible(false);
                }
                else if (seleccion == 2){
                    mascota3.setVisible(false);
                    nombremascota3.setVisible(false);
                    textFieldnombremascota3.setVisible(false);
                    tipomascota3.setVisible(false);
                    JComboBoxtipomascota3.setVisible(false);
                    razamascota3.setVisible(false);
                    textFieldrazamascota3.setVisible(false);
                    edadmascota3.setVisible(false);
                    textFieldedadmascota3.setVisible(false);
                    sexomascota3.setVisible(false);
                    JComboBoxsexomascota3.setVisible(false);
                    alimentomascota3.setVisible(false);
                    JComboBoxalimentomascota3.setVisible(false);

                    mascota4.setVisible(false);
                    nombremascota4.setVisible(false);
                    textFieldnombremascota4.setVisible(false);
                    tipomascota4.setVisible(false);
                    JComboBoxtipomascota4.setVisible(false);
                    razamascota4.setVisible(false);
                    textFieldrazamascota4.setVisible(false);
                    edadmascota4.setVisible(false);
                    textFieldedadmascota4.setVisible(false);
                    sexomascota4.setVisible(false);
                    JComboBoxsexomascota4.setVisible(false);
                    alimentomascota4.setVisible(false);
                    JComboBoxalimentomascota4.setVisible(false);

                    mascota5.setVisible(false);
                    nombremascota5.setVisible(false);
                    textFieldnombremascota5.setVisible(false);
                    tipomascota5.setVisible(false);
                    JComboBoxtipomascota5.setVisible(false);
                    razamascota5.setVisible(false);
                    textFieldrazamascota5.setVisible(false);
                    edadmascota5.setVisible(false);
                    textFieldedadmascota5.setVisible(false);
                    sexomascota5.setVisible(false);
                    JComboBoxsexomascota5.setVisible(false);
                    alimentomascota5.setVisible(false);
                    JComboBoxalimentomascota5.setVisible(false);

                    mascota6.setVisible(false);
                    nombremascota6.setVisible(false);
                    textFieldnombremascota6.setVisible(false);
                    tipomascota6.setVisible(false);
                    JComboBoxtipomascota6.setVisible(false);
                    razamascota6.setVisible(false);
                    textFieldrazamascota6.setVisible(false);
                    edadmascota6.setVisible(false);
                    textFieldedadmascota6.setVisible(false);
                    sexomascota6.setVisible(false);
                    JComboBoxsexomascota6.setVisible(false);
                    alimentomascota6.setVisible(false);
                    JComboBoxalimentomascota6.setVisible(false);

                    mascota7.setVisible(false);
                    nombremascota7.setVisible(false);
                    textFieldnombremascota7.setVisible(false);
                    tipomascota7.setVisible(false);
                    JComboBoxtipomascota7.setVisible(false);
                    razamascota7.setVisible(false);
                    textFieldrazamascota7.setVisible(false);
                    edadmascota7.setVisible(false);
                    textFieldedadmascota7.setVisible(false);
                    sexomascota7.setVisible(false);
                    JComboBoxsexomascota7.setVisible(false);
                    alimentomascota7.setVisible(false);
                    JComboBoxalimentomascota7.setVisible(false);

                    mascota8.setVisible(false);
                    nombremascota8.setVisible(false);
                    textFieldnombremascota8.setVisible(false);
                    tipomascota8.setVisible(false);
                    JComboBoxtipomascota8.setVisible(false);
                    razamascota8.setVisible(false);
                    textFieldrazamascota8.setVisible(false);
                    edadmascota8.setVisible(false);
                    textFieldedadmascota8.setVisible(false);
                    sexomascota8.setVisible(false);
                    JComboBoxsexomascota8.setVisible(false);
                    alimentomascota8.setVisible(false);
                    JComboBoxalimentomascota8.setVisible(false);

                    mascota9.setVisible(false);
                    nombremascota9.setVisible(false);
                    textFieldnombremascota9.setVisible(false);
                    tipomascota9.setVisible(false);
                    JComboBoxtipomascota9.setVisible(false);
                    razamascota9.setVisible(false);
                    textFieldrazamascota9.setVisible(false);
                    edadmascota9.setVisible(false);
                    textFieldedadmascota9.setVisible(false);
                    sexomascota9.setVisible(false);
                    JComboBoxsexomascota9.setVisible(false);
                    alimentomascota9.setVisible(false);
                    JComboBoxalimentomascota9.setVisible(false);
                }
                else if (seleccion == 3){
                    mascota4.setVisible(false);
                    nombremascota4.setVisible(false);
                    textFieldnombremascota4.setVisible(false);
                    tipomascota4.setVisible(false);
                    JComboBoxtipomascota4.setVisible(false);
                    razamascota4.setVisible(false);
                    textFieldrazamascota4.setVisible(false);
                    edadmascota4.setVisible(false);
                    textFieldedadmascota4.setVisible(false);
                    sexomascota4.setVisible(false);
                    JComboBoxsexomascota4.setVisible(false);
                    alimentomascota4.setVisible(false);
                    JComboBoxalimentomascota4.setVisible(false);

                    mascota5.setVisible(false);
                    nombremascota5.setVisible(false);
                    textFieldnombremascota5.setVisible(false);
                    tipomascota5.setVisible(false);
                    JComboBoxtipomascota5.setVisible(false);
                    razamascota5.setVisible(false);
                    textFieldrazamascota5.setVisible(false);
                    edadmascota5.setVisible(false);
                    textFieldedadmascota5.setVisible(false);
                    sexomascota5.setVisible(false);
                    JComboBoxsexomascota5.setVisible(false);
                    alimentomascota5.setVisible(false);
                    JComboBoxalimentomascota5.setVisible(false);

                    mascota6.setVisible(false);
                    nombremascota6.setVisible(false);
                    textFieldnombremascota6.setVisible(false);
                    tipomascota6.setVisible(false);
                    JComboBoxtipomascota6.setVisible(false);
                    razamascota6.setVisible(false);
                    textFieldrazamascota6.setVisible(false);
                    edadmascota6.setVisible(false);
                    textFieldedadmascota6.setVisible(false);
                    sexomascota6.setVisible(false);
                    JComboBoxsexomascota6.setVisible(false);
                    alimentomascota6.setVisible(false);
                    JComboBoxalimentomascota6.setVisible(false);

                    mascota7.setVisible(false);
                    nombremascota7.setVisible(false);
                    textFieldnombremascota7.setVisible(false);
                    tipomascota7.setVisible(false);
                    JComboBoxtipomascota7.setVisible(false);
                    razamascota7.setVisible(false);
                    textFieldrazamascota7.setVisible(false);
                    edadmascota7.setVisible(false);
                    textFieldedadmascota7.setVisible(false);
                    sexomascota7.setVisible(false);
                    JComboBoxsexomascota7.setVisible(false);
                    alimentomascota7.setVisible(false);
                    JComboBoxalimentomascota7.setVisible(false);

                    mascota8.setVisible(false);
                    nombremascota8.setVisible(false);
                    textFieldnombremascota8.setVisible(false);
                    tipomascota8.setVisible(false);
                    JComboBoxtipomascota8.setVisible(false);
                    razamascota8.setVisible(false);
                    textFieldrazamascota8.setVisible(false);
                    edadmascota8.setVisible(false);
                    textFieldedadmascota8.setVisible(false);
                    sexomascota8.setVisible(false);
                    JComboBoxsexomascota8.setVisible(false);
                    alimentomascota8.setVisible(false);
                    JComboBoxalimentomascota8.setVisible(false);

                    mascota9.setVisible(false);
                    nombremascota9.setVisible(false);
                    textFieldnombremascota9.setVisible(false);
                    tipomascota9.setVisible(false);
                    JComboBoxtipomascota9.setVisible(false);
                    razamascota9.setVisible(false);
                    textFieldrazamascota9.setVisible(false);
                    edadmascota9.setVisible(false);
                    textFieldedadmascota9.setVisible(false);
                    sexomascota9.setVisible(false);
                    JComboBoxsexomascota9.setVisible(false);
                    alimentomascota9.setVisible(false);
                    JComboBoxalimentomascota9.setVisible(false);
                }
                else if (seleccion == 4){
                    mascota5.setVisible(false);
                    nombremascota5.setVisible(false);
                    textFieldnombremascota5.setVisible(false);
                    tipomascota5.setVisible(false);
                    JComboBoxtipomascota5.setVisible(false);
                    razamascota5.setVisible(false);
                    textFieldrazamascota5.setVisible(false);
                    edadmascota5.setVisible(false);
                    textFieldedadmascota5.setVisible(false);
                    sexomascota5.setVisible(false);
                    JComboBoxsexomascota5.setVisible(false);
                    alimentomascota5.setVisible(false);
                    JComboBoxalimentomascota5.setVisible(false);

                    mascota6.setVisible(false);
                    nombremascota6.setVisible(false);
                    textFieldnombremascota6.setVisible(false);
                    tipomascota6.setVisible(false);
                    JComboBoxtipomascota6.setVisible(false);
                    razamascota6.setVisible(false);
                    textFieldrazamascota6.setVisible(false);
                    edadmascota6.setVisible(false);
                    textFieldedadmascota6.setVisible(false);
                    sexomascota6.setVisible(false);
                    JComboBoxsexomascota6.setVisible(false);
                    alimentomascota6.setVisible(false);
                    JComboBoxalimentomascota6.setVisible(false);

                    mascota7.setVisible(false);
                    nombremascota7.setVisible(false);
                    textFieldnombremascota7.setVisible(false);
                    tipomascota7.setVisible(false);
                    JComboBoxtipomascota7.setVisible(false);
                    razamascota7.setVisible(false);
                    textFieldrazamascota7.setVisible(false);
                    edadmascota7.setVisible(false);
                    textFieldedadmascota7.setVisible(false);
                    sexomascota7.setVisible(false);
                    JComboBoxsexomascota7.setVisible(false);
                    alimentomascota7.setVisible(false);
                    JComboBoxalimentomascota7.setVisible(false);

                    mascota8.setVisible(false);
                    nombremascota8.setVisible(false);
                    textFieldnombremascota8.setVisible(false);
                    tipomascota8.setVisible(false);
                    JComboBoxtipomascota8.setVisible(false);
                    razamascota8.setVisible(false);
                    textFieldrazamascota8.setVisible(false);
                    edadmascota8.setVisible(false);
                    textFieldedadmascota8.setVisible(false);
                    sexomascota8.setVisible(false);
                    JComboBoxsexomascota8.setVisible(false);
                    alimentomascota8.setVisible(false);
                    JComboBoxalimentomascota8.setVisible(false);

                    mascota9.setVisible(false);
                    nombremascota9.setVisible(false);
                    textFieldnombremascota9.setVisible(false);
                    tipomascota9.setVisible(false);
                    JComboBoxtipomascota9.setVisible(false);
                    razamascota9.setVisible(false);
                    textFieldrazamascota9.setVisible(false);
                    edadmascota9.setVisible(false);
                    textFieldedadmascota9.setVisible(false);
                    sexomascota9.setVisible(false);
                    JComboBoxsexomascota9.setVisible(false);
                    alimentomascota9.setVisible(false);
                    JComboBoxalimentomascota9.setVisible(false);
                }
                else if (seleccion == 5){
                    mascota6.setVisible(false);
                    nombremascota6.setVisible(false);
                    textFieldnombremascota6.setVisible(false);
                    tipomascota6.setVisible(false);
                    JComboBoxtipomascota6.setVisible(false);
                    razamascota6.setVisible(false);
                    textFieldrazamascota6.setVisible(false);
                    edadmascota6.setVisible(false);
                    textFieldedadmascota6.setVisible(false);
                    sexomascota6.setVisible(false);
                    JComboBoxsexomascota6.setVisible(false);
                    alimentomascota6.setVisible(false);
                    JComboBoxalimentomascota6.setVisible(false);

                    mascota7.setVisible(false);
                    nombremascota7.setVisible(false);
                    textFieldnombremascota7.setVisible(false);
                    tipomascota7.setVisible(false);
                    JComboBoxtipomascota7.setVisible(false);
                    razamascota7.setVisible(false);
                    textFieldrazamascota7.setVisible(false);
                    edadmascota7.setVisible(false);
                    textFieldedadmascota7.setVisible(false);
                    sexomascota7.setVisible(false);
                    JComboBoxsexomascota7.setVisible(false);
                    alimentomascota7.setVisible(false);
                    JComboBoxalimentomascota7.setVisible(false);

                    mascota8.setVisible(false);
                    nombremascota8.setVisible(false);
                    textFieldnombremascota8.setVisible(false);
                    tipomascota8.setVisible(false);
                    JComboBoxtipomascota8.setVisible(false);
                    razamascota8.setVisible(false);
                    textFieldrazamascota8.setVisible(false);
                    edadmascota8.setVisible(false);
                    textFieldedadmascota8.setVisible(false);
                    sexomascota8.setVisible(false);
                    JComboBoxsexomascota8.setVisible(false);
                    alimentomascota8.setVisible(false);
                    JComboBoxalimentomascota8.setVisible(false);

                    mascota9.setVisible(false);
                    nombremascota9.setVisible(false);
                    textFieldnombremascota9.setVisible(false);
                    tipomascota9.setVisible(false);
                    JComboBoxtipomascota9.setVisible(false);
                    razamascota9.setVisible(false);
                    textFieldrazamascota9.setVisible(false);
                    edadmascota9.setVisible(false);
                    textFieldedadmascota9.setVisible(false);
                    sexomascota9.setVisible(false);
                    JComboBoxsexomascota9.setVisible(false);
                    alimentomascota9.setVisible(false);
                    JComboBoxalimentomascota9.setVisible(false);
                }
                else if (seleccion == 6){
                    mascota7.setVisible(false);
                    nombremascota7.setVisible(false);
                    textFieldnombremascota7.setVisible(false);
                    tipomascota7.setVisible(false);
                    JComboBoxtipomascota7.setVisible(false);
                    razamascota7.setVisible(false);
                    textFieldrazamascota7.setVisible(false);
                    edadmascota7.setVisible(false);
                    textFieldedadmascota7.setVisible(false);
                    sexomascota7.setVisible(false);
                    JComboBoxsexomascota7.setVisible(false);
                    alimentomascota7.setVisible(false);
                    JComboBoxalimentomascota7.setVisible(false);

                    mascota8.setVisible(false);
                    nombremascota8.setVisible(false);
                    textFieldnombremascota8.setVisible(false);
                    tipomascota8.setVisible(false);
                    JComboBoxtipomascota8.setVisible(false);
                    razamascota8.setVisible(false);
                    textFieldrazamascota8.setVisible(false);
                    edadmascota8.setVisible(false);
                    textFieldedadmascota8.setVisible(false);
                    sexomascota8.setVisible(false);
                    JComboBoxsexomascota8.setVisible(false);
                    alimentomascota8.setVisible(false);
                    JComboBoxalimentomascota8.setVisible(false);

                    mascota9.setVisible(false);
                    nombremascota9.setVisible(false);
                    textFieldnombremascota9.setVisible(false);
                    tipomascota9.setVisible(false);
                    JComboBoxtipomascota9.setVisible(false);
                    razamascota9.setVisible(false);
                    textFieldrazamascota9.setVisible(false);
                    edadmascota9.setVisible(false);
                    textFieldedadmascota9.setVisible(false);
                    sexomascota9.setVisible(false);
                    JComboBoxsexomascota9.setVisible(false);
                    alimentomascota9.setVisible(false);
                    JComboBoxalimentomascota9.setVisible(false);
                }
                else if (seleccion == 7){
                    mascota8.setVisible(false);
                    nombremascota8.setVisible(false);
                    textFieldnombremascota8.setVisible(false);
                    tipomascota8.setVisible(false);
                    JComboBoxtipomascota8.setVisible(false);
                    razamascota8.setVisible(false);
                    textFieldrazamascota8.setVisible(false);
                    edadmascota8.setVisible(false);
                    textFieldedadmascota8.setVisible(false);
                    sexomascota8.setVisible(false);
                    JComboBoxsexomascota8.setVisible(false);
                    alimentomascota8.setVisible(false);
                    JComboBoxalimentomascota8.setVisible(false);

                    mascota9.setVisible(false);
                    nombremascota9.setVisible(false);
                    textFieldnombremascota9.setVisible(false);
                    tipomascota9.setVisible(false);
                    JComboBoxtipomascota9.setVisible(false);
                    razamascota9.setVisible(false);
                    textFieldrazamascota9.setVisible(false);
                    edadmascota9.setVisible(false);
                    textFieldedadmascota9.setVisible(false);
                    sexomascota9.setVisible(false);
                    JComboBoxsexomascota9.setVisible(false);
                    alimentomascota9.setVisible(false);
                    JComboBoxalimentomascota9.setVisible(false);
                }
                else if (seleccion == 8){
                    mascota9.setVisible(false);
                    nombremascota9.setVisible(false);
                    textFieldnombremascota9.setVisible(false);
                    tipomascota9.setVisible(false);
                    JComboBoxtipomascota9.setVisible(false);
                    razamascota9.setVisible(false);
                    textFieldrazamascota9.setVisible(false);
                    edadmascota9.setVisible(false);
                    textFieldedadmascota9.setVisible(false);
                    sexomascota9.setVisible(false);
                    JComboBoxsexomascota9.setVisible(false);
                    alimentomascota9.setVisible(false);
                    JComboBoxalimentomascota9.setVisible(false);
                }
                else
                    mascota9.setVisible(true);
            }
        });
        mostrarContraseñaCheckBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (mostrarContraseñaCheckBox.isSelected()){
                    passwordField2.setEchoChar((char)0);
                }
                else
                    passwordField2.setEchoChar('*');
            }
        });
    };
    public JPanel getCrearusuario() {
        return crearusuario;
    }
}